<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260209221725 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "groups" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, act VARCHAR(255) DEFAULT NULL, institution_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F06D397010405986 ON "groups" (institution_id)');
        $this->addSql('CREATE TABLE institution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, registrar_email VARCHAR(180) NOT NULL, identifier VARCHAR(100) DEFAULT NULL, type VARCHAR(50) NOT NULL, contact_person VARCHAR(255) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zip VARCHAR(10) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3A9F98E54AE5A92E ON institution (registrar_email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3A9F98E5772E836A ON institution (identifier)');
        $this->addSql('CREATE TABLE sportabzeichen_disciplines (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, einheit VARCHAR(50) NOT NULL, kategorie VARCHAR(50) NOT NULL, berechnungsart TEXT DEFAULT \'GREATER\' NOT NULL, verband TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE sportabzeichen_exam_participants (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, age_year INT NOT NULL, total_points INT DEFAULT 0 NOT NULL, final_medal VARCHAR(10) DEFAULT \'NONE\' NOT NULL, exam_id INT NOT NULL, participant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B0129C27578D5E91 ON sportabzeichen_exam_participants (exam_id)');
        $this->addSql('CREATE INDEX IDX_B0129C279D1C3019 ON sportabzeichen_exam_participants (participant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_exam_participant ON sportabzeichen_exam_participants (exam_id, participant_id)');
        $this->addSql('CREATE TABLE sportabzeichen_exam_results (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, leistung DOUBLE PRECISION DEFAULT NULL, stufe TEXT DEFAULT NULL, points INT NOT NULL, ep_id INT NOT NULL, discipline_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_27BBCB965CFB39E ON sportabzeichen_exam_results (ep_id)');
        $this->addSql('CREATE INDEX IDX_27BBCB9A5522701 ON sportabzeichen_exam_results (discipline_id)');
        $this->addSql('CREATE TABLE sportabzeichen_exams (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exam_name VARCHAR(255) NOT NULL, exam_year INT NOT NULL, exam_date DATE DEFAULT NULL, creator_id VARCHAR(255) DEFAULT NULL, institution_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FC8CC66C10405986 ON sportabzeichen_exams (institution_id)');
        $this->addSql('CREATE TABLE sportabzeichen_exam_groups (exam_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY (exam_id, group_id))');
        $this->addSql('CREATE INDEX IDX_FA423BF5578D5E91 ON sportabzeichen_exam_groups (exam_id)');
        $this->addSql('CREATE INDEX IDX_FA423BF5FE54D947 ON sportabzeichen_exam_groups (group_id)');
        $this->addSql('CREATE TABLE sportabzeichen_participants (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, geburtsdatum DATE DEFAULT NULL, geschlecht VARCHAR(10) DEFAULT NULL, origin VARCHAR(50) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, group_name VARCHAR(255) DEFAULT NULL, institution_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E117715710405986 ON sportabzeichen_participants (institution_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E1177157A76ED395 ON sportabzeichen_participants (user_id)');
        $this->addSql('CREATE TABLE sportabzeichen_requirements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jahr INT NOT NULL, age_min INT NOT NULL, age_max INT NOT NULL, geschlecht TEXT NOT NULL, auswahlnummer INT NOT NULL, bronze DOUBLE PRECISION DEFAULT NULL, silber DOUBLE PRECISION DEFAULT NULL, gold DOUBLE PRECISION DEFAULT NULL, schwimmnachweis BOOLEAN DEFAULT false NOT NULL, discipline_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E0C0A06FA5522701 ON sportabzeichen_requirements (discipline_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_sportabzeichen_requirements ON sportabzeichen_requirements (discipline_id, jahr, age_min, age_max, geschlecht)');
        $this->addSql('CREATE TABLE sportabzeichen_swimming_proofs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, confirmed_at DATE NOT NULL, valid_until DATE NOT NULL, requirement_met_via VARCHAR(255) DEFAULT NULL, exam_year INT DEFAULT NULL, participant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_36FC89689D1C3019 ON sportabzeichen_swimming_proofs (participant_id)');
        $this->addSql('CREATE TABLE sportabzeichen_training (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, value VARCHAR(255) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, discipline_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EB1E516DA76ED395 ON sportabzeichen_training (user_id)');
        $this->addSql('CREATE INDEX IDX_EB1E516DA5522701 ON sportabzeichen_training (discipline_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_discipline_year ON sportabzeichen_training (user_id, discipline_id, year)');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) DEFAULT NULL, username VARCHAR(180) DEFAULT NULL, act VARCHAR(255) DEFAULT NULL, source VARCHAR(50) DEFAULT \'iserv\' NOT NULL, import_id VARCHAR(255) DEFAULT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(255) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, institution_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9F85E0677 ON users (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9B6A263D9 ON users (import_id)');
        $this->addSql('CREATE INDEX IDX_1483A5E910405986 ON users (institution_id)');
        $this->addSql('CREATE TABLE users_groups (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY (user_id, group_id))');
        $this->addSql('CREATE INDEX IDX_FF8AB7E0A76ED395 ON users_groups (user_id)');
        $this->addSql('CREATE INDEX IDX_FF8AB7E0FE54D947 ON users_groups (group_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE "groups" ADD CONSTRAINT FK_F06D397010405986 FOREIGN KEY (institution_id) REFERENCES institution (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_exam_participants ADD CONSTRAINT FK_B0129C27578D5E91 FOREIGN KEY (exam_id) REFERENCES sportabzeichen_exams (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_exam_participants ADD CONSTRAINT FK_B0129C279D1C3019 FOREIGN KEY (participant_id) REFERENCES sportabzeichen_participants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_exam_results ADD CONSTRAINT FK_27BBCB965CFB39E FOREIGN KEY (ep_id) REFERENCES sportabzeichen_exam_participants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_exam_results ADD CONSTRAINT FK_27BBCB9A5522701 FOREIGN KEY (discipline_id) REFERENCES sportabzeichen_disciplines (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_exams ADD CONSTRAINT FK_FC8CC66C10405986 FOREIGN KEY (institution_id) REFERENCES institution (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_exam_groups ADD CONSTRAINT FK_FA423BF5578D5E91 FOREIGN KEY (exam_id) REFERENCES sportabzeichen_exams (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sportabzeichen_exam_groups ADD CONSTRAINT FK_FA423BF5FE54D947 FOREIGN KEY (group_id) REFERENCES "groups" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE sportabzeichen_participants ADD CONSTRAINT FK_E117715710405986 FOREIGN KEY (institution_id) REFERENCES institution (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_participants ADD CONSTRAINT FK_E1177157A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_requirements ADD CONSTRAINT FK_E0C0A06FA5522701 FOREIGN KEY (discipline_id) REFERENCES sportabzeichen_disciplines (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_swimming_proofs ADD CONSTRAINT FK_36FC89689D1C3019 FOREIGN KEY (participant_id) REFERENCES sportabzeichen_participants (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_training ADD CONSTRAINT FK_EB1E516DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sportabzeichen_training ADD CONSTRAINT FK_EB1E516DA5522701 FOREIGN KEY (discipline_id) REFERENCES sportabzeichen_disciplines (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT FK_1483A5E910405986 FOREIGN KEY (institution_id) REFERENCES institution (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users_groups ADD CONSTRAINT FK_FF8AB7E0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE users_groups ADD CONSTRAINT FK_FF8AB7E0FE54D947 FOREIGN KEY (group_id) REFERENCES "groups" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE "groups" DROP CONSTRAINT FK_F06D397010405986');
        $this->addSql('ALTER TABLE sportabzeichen_exam_participants DROP CONSTRAINT FK_B0129C27578D5E91');
        $this->addSql('ALTER TABLE sportabzeichen_exam_participants DROP CONSTRAINT FK_B0129C279D1C3019');
        $this->addSql('ALTER TABLE sportabzeichen_exam_results DROP CONSTRAINT FK_27BBCB965CFB39E');
        $this->addSql('ALTER TABLE sportabzeichen_exam_results DROP CONSTRAINT FK_27BBCB9A5522701');
        $this->addSql('ALTER TABLE sportabzeichen_exams DROP CONSTRAINT FK_FC8CC66C10405986');
        $this->addSql('ALTER TABLE sportabzeichen_exam_groups DROP CONSTRAINT FK_FA423BF5578D5E91');
        $this->addSql('ALTER TABLE sportabzeichen_exam_groups DROP CONSTRAINT FK_FA423BF5FE54D947');
        $this->addSql('ALTER TABLE sportabzeichen_participants DROP CONSTRAINT FK_E117715710405986');
        $this->addSql('ALTER TABLE sportabzeichen_participants DROP CONSTRAINT FK_E1177157A76ED395');
        $this->addSql('ALTER TABLE sportabzeichen_requirements DROP CONSTRAINT FK_E0C0A06FA5522701');
        $this->addSql('ALTER TABLE sportabzeichen_swimming_proofs DROP CONSTRAINT FK_36FC89689D1C3019');
        $this->addSql('ALTER TABLE sportabzeichen_training DROP CONSTRAINT FK_EB1E516DA76ED395');
        $this->addSql('ALTER TABLE sportabzeichen_training DROP CONSTRAINT FK_EB1E516DA5522701');
        $this->addSql('ALTER TABLE users DROP CONSTRAINT FK_1483A5E910405986');
        $this->addSql('ALTER TABLE users_groups DROP CONSTRAINT FK_FF8AB7E0A76ED395');
        $this->addSql('ALTER TABLE users_groups DROP CONSTRAINT FK_FF8AB7E0FE54D947');
        $this->addSql('DROP TABLE "groups"');
        $this->addSql('DROP TABLE institution');
        $this->addSql('DROP TABLE sportabzeichen_disciplines');
        $this->addSql('DROP TABLE sportabzeichen_exam_participants');
        $this->addSql('DROP TABLE sportabzeichen_exam_results');
        $this->addSql('DROP TABLE sportabzeichen_exams');
        $this->addSql('DROP TABLE sportabzeichen_exam_groups');
        $this->addSql('DROP TABLE sportabzeichen_participants');
        $this->addSql('DROP TABLE sportabzeichen_requirements');
        $this->addSql('DROP TABLE sportabzeichen_swimming_proofs');
        $this->addSql('DROP TABLE sportabzeichen_training');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE users_groups');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
